// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTT.Repository.Context;

#nullable disable

namespace NTT.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231108191427_Initial5")]
    partial class Initial5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NTT.Core.Entity.TelephoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TelephoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5860),
                            TelNo = "05321234567",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5860),
                            TelNo = "05321234568",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5870),
                            TelNo = "05321234569",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5870),
                            TelNo = "05321234570",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("NTT.Core.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5630),
                            Email = "johndoe@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            TcNo = "12345678901",
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5680),
                            Email = "georgebush@gmail.com",
                            FirstName = "George",
                            LastName = "Bush",
                            TcNo = "55345678901",
                            Username = "georgebush"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5680),
                            Email = "michealjack@gmail.com",
                            FirstName = "Michael",
                            LastName = "Jackson",
                            TcNo = "12345678901",
                            Username = "michaeljackson"
                        });
                });

            modelBuilder.Entity("NTT.Core.Entity.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5820),
                            RoleType = "User",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5820),
                            RoleType = "Admin",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5820),
                            RoleType = "Admin",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 11, 8, 22, 14, 27, 217, DateTimeKind.Local).AddTicks(5820),
                            RoleType = "Guest",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("NTT.Core.Entity.TelephoneNumber", b =>
                {
                    b.HasOne("NTT.Core.Entity.User", "User")
                        .WithMany("TelephoneNumbers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NTT.Core.Entity.UserRole", b =>
                {
                    b.HasOne("NTT.Core.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NTT.Core.Entity.User", b =>
                {
                    b.Navigation("TelephoneNumbers");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
